### ISSUE TITLE
Add library.properties or library.json

### ISSUE THREAD

**Issue by SRGDamia1** [SlashDevin/NeoSWSerial#11]
It would be nice if one of these existed for the IDE and the library was registered with PlatformIO.

**Comment by SRGDamia1** [comment]
Wow, that was fast.  Awesome!

**Comment by SlashDevin** [comment]
It has been submitted to the Arduino Library Manager.  I'll close this when it has been accepted.

**Comment by SlashDevin** [comment]
Be sure to get `v3.0.2`.
