### ISSUE TITLE
#error MCU not supported by NeoSWSerial!

### ISSUE THREAD

**Issue by ThierryGo1** [SlashDevin/NeoSWSerial#25]
Is Intel Currie (UDOO board, genuino 101) supported by NeoSWSerial ?
And, does exist it any modification to do for work correctly ?

**Comment by SlashDevin** [comment]
No.  The hardware is quite different.  NeoSWSerial is for AVR 8-bit hardware (UNO, Mega, Tiny, etc.)

**Comment by ThierryGo1** [comment]
OK, TU
Thierry
