### ISSUE TITLE
RX/TX on the atmega1284

### ISSUE THREAD

**Issue by nzfarmer1** [SlashDevin/NeoSWSerial#6]
Am attempting to find a solution that will enable us to write to our atmega1284p using your library as a drop in for SoftwareSerial.

RX is fine, but TX to the device fails. This appears to be a known issue:
http://forum.arduino.cc/index.php?topic=360158.15

Have tried your library (and a few others) using digital pins 17,18 PCINT17, PCINT18 but have been unsuccessful to date.

**Comment by SlashDevin** [comment]
After investigating a similar report a few months ago, I found a problem in the mighty core, not NeoSWSerial.  Could you take a look at [this discussion](https://forum.arduino.cc/index.php?topic=262983.msg2892871#msg2892871) and see if getting the revised core works?  Reply 15 points to the updated core, and reply 16 is from the maintainer.
