### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dionorgua** [SlashDevin/NeoSWSerial#8]
Hi,

Could you please clarify license for NeoSWSerial class? Is it same LGPL2.1+ as NeoGPS?

Thanks!

**Comment by SlashDevin** [comment]
Right, I'll investigate...

**Comment by SlashDevin** [comment]
After a little consideration, I've opted for GPL instead of LGPL...

**Comment by dionorgua** [comment]
ok. Thanks!
